package com.rental.entity.enums;

public enum OrderStatus {
    PENDING,
    ACCEPTED,
    REJECTED,
    RENTED,
    RETURN_REQUESTED,
    RETURN_INSPECTION_PENDING,
    RETURN_CONFIRMED,
    DAMAGE_REPORTED,
    ACTIVE,
    RETURNED,
    CANCELLED,
    CANCELLED_BY_CUSTOMER,
    CANCELLED_BY_VENDOR
}
